/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-11 11:15:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import java.time.format.DateTimeFormatter;
import fr.simplon.models.Post;
import fr.simplon.models.User;

public final class feed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("fr.simplon.models.User");
    _jspx_imports_classes.add("fr.simplon.models.Post");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User currentUser = (User) request.getAttribute("currentUser");
    String tab = (String) request.getAttribute("tab");
    List<Post> posts = (List<Post>) request.getAttribute("posts");
    Map<Long, String> postOwnerNames = (Map<Long, String>) request.getAttribute("postOwnerNames");
    Map<Long, Long> postOwnerIds = (Map<Long, Long>) request.getAttribute("postOwnerIds");
    Map<Long, Long> postLikeCounts = (Map<Long, Long>) request.getAttribute("postLikeCounts");
    Map<Long, Boolean> postLikedByUser = (Map<Long, Boolean>) request.getAttribute("postLikedByUser");
    Map<Long, Long> postCommentCounts = (Map<Long, Long>) request.getAttribute("postCommentCounts");
    DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Miniature - Fil d'actualité</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/app.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"top-bar\">\r\n");
      out.write("        <h1 class=\"logo\"><a href=\"/feed\">Miniature</a></h1>\r\n");
      out.write("        <div class=\"top-bar-right\">\r\n");
      out.write("            <a href=\"/profile\" class=\"current-user-link\">");
      out.print(currentUser.getUsername());
      out.write("</a>\r\n");
      out.write("            <form method=\"post\" action=\"/logout\" class=\"inline-form\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger btn-sm\">Déconnexion</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <!-- Onglets -->\r\n");
      out.write("        <nav class=\"tabs\">\r\n");
      out.write("            <a href=\"/feed?tab=recommendations\" class=\"tab ");
      out.print( "recommendations".equals(tab) ? "active" : "" );
      out.write("\">\r\n");
      out.write("                Recommandations\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"/feed?tab=subscriptions\" class=\"tab ");
      out.print( "subscriptions".equals(tab) ? "active" : "" );
      out.write("\">\r\n");
      out.write("                Abonnements\r\n");
      out.write("            </a>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- Formulaire nouveau post -->\r\n");
      out.write("        <form method=\"post\" action=\"/feed\" class=\"new-post-form\">\r\n");
      out.write("            <input type=\"hidden\" name=\"tab\" value=\"");
      out.print(tab);
      out.write("\" />\r\n");
      out.write("            <textarea name=\"content\" placeholder=\"Quoi de neuf ?\" required rows=\"3\"></textarea>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">Publier</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <!-- Liste des posts -->\r\n");
      out.write("        ");
 if (posts == null || posts.isEmpty()) { 
      out.write("\r\n");
      out.write("            <p class=\"empty-message\">Aucun post à afficher.</p>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <div class=\"post-list\">\r\n");
      out.write("            ");
 for (Post post : posts) {
                String ownerName = postOwnerNames.get(post.getId());
                long ownerId = postOwnerIds.get(post.getId());
                long likes = postLikeCounts.get(post.getId());
                boolean liked = postLikedByUser.get(post.getId());
                long commentCount = postCommentCounts.get(post.getId());
            
      out.write("\r\n");
      out.write("                <article class=\"post-card\">\r\n");
      out.write("                    <div class=\"post-header\">\r\n");
      out.write("                        <a href=\"/profile?id=");
      out.print(ownerId);
      out.write("\" class=\"post-author-link\"><strong class=\"post-author\">");
      out.print(ownerName);
      out.write("</strong></a>\r\n");
      out.write("                        <time class=\"post-date\">");
      out.print(post.getCreatedAt().format(fmt));
      out.write("</time>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p class=\"post-content\">");
      out.print(post.getContent());
      out.write("</p>\r\n");
      out.write("                    <div class=\"post-actions\">\r\n");
      out.write("                        <form method=\"post\" action=\"/like\" class=\"inline-form\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"postId\" value=\"");
      out.print(post.getId());
      out.write("\" />\r\n");
      out.write("                            <input type=\"hidden\" name=\"redirect\" value=\"/feed?tab=");
      out.print(tab);
      out.write("\" />\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-action ");
      out.print( liked ? "liked" : "" );
      out.write("\">\r\n");
      out.write("                                ");
      out.print( liked ? "&#9829;" : "&#9825;" );
      out.write(' ');
      out.print(likes);
      out.write("\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <a href=\"/post?id=");
      out.print(post.getId());
      out.write("\" class=\"btn-action\">\r\n");
      out.write("                            &#128172; ");
      out.print(commentCount);
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </article>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
